apiVersion: v1
kind: Service
metadata:
  name: helloworld-statefull
spec:
  clusterIP: None
  selector:
    app: mytest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld-statefull
  labels:
    app: helloworld-statefull
spec:
  serviceName: helloworld-statefull
  replicas: 3
  selector:
    matchLabels:
      app: mytest
  template:
    metadata:
      labels:
        app: mytest
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.0.0.10
        searches:
          - helloworld-statefull.default.svc.cluster.local
          - default.svc.cluster.locl
          - svc.cluster.local
          - cluster.local
          - us-west2-c.c.k8s-training-277307.internal
          - c.k8s-training-277307.internal
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: node-port
          containerPort: 80
